### PR TITLE
Added: "hideemail" field variable

### PR DESCRIPTION
**Pull request by contemplate**
now you can add:
"hideemail"=>true
to the register helper field array to remove a field from being included in the admin email

### CODE REVIEW

**Comment by strangerstudios** [comment]
How about adminemail=>false if you want to hide it? We could default it to true. And I would maybe create a function pmprorh_getAdminEmailFields like pmprorh_getProfileFields that would return only fields for the email and loop through those when outputting the fields in the email.

**Comment by contemplate** [comment]
Oh I like that idea better!  Although certain fields we would want hidden on the admin email as well as the member's email.

Will you make these improvements or would you like me to take a crack at it?

**Comment by strangerstudios** [comment]
The addon as is only adds the fields to the admin email... I think we did it that way to avoid issues around which fields should be visible to members in email vs just admins.

Are you using custom code to include the meta fields in the member confirmation emails?

Instead of adminemail, we could make the setting "email" with the default option to send it to admins but not users (current behavior). Options could then be false, true (both), "only_admin", or "only_member"

Something like that.

If you're up for coding this, I would appreciate the help.

**Comment by contemplate** [comment]
No we aren't sending the fields to the members.  And prefer to not have any of the fields going to the member.  I guess I had read your previous comment about the functions incorrectly.  So yes no need to send to the member.  

I hope to carve out some time next week to work on this.  Thanks!

**Comment by strangerstudios** [comment]
I still like this idea. Let me know if you'll have time to work on it, or I can pull in your change and have someone on our team fix it up per our comments here. Thanks.

**Comment by contemplate** [comment]
@strangerstudios that would be great if you all wanted to go ahead and do it!

**Comment by dparker1005** [comment]
This is an idea that we would like to look further into, but that will require additional changes to be made that are not scheduled at this time. For this reason, I have created an issue here to track this enhancement and am going to close this pull request: https://github.com/strangerstudios/pmpro-register-helper/issues/185

**Pull request closed without merging**
